name: tts
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - cudatoolkit=10.2
  - pytorch==1.6.0
  - tensorflow==2.3.0
  - h5py==2.10.0
  - hdf5=1.10.
  - tensorboard=2.3.0
  - numba=0.48
  - scipy
  - librosa=0.7.2
  - unidecode
  - attrdict
  - tensorboardx
  - matplotlib
  - inflect
  - tqdm
  - flask
  - pillow
  - bokeh=1.4.0
  - fuzzywuzzy
  - num2words
  - gdown
  - nose=1.3.7
  - pylint=2.5.3
  - ffmpeg
  - pip:
    - cardboardlint==1.3.0
    - phonemizer==2.2.1
    - pysbd
